namespace Zentient.Reflector.Disassembler;

public enum CilOpcode
{
    Nop = 0x00,
    Break = 0x01,
    Ldarg_0 = 0x02,
    Ldarg_1 = 0x03,
    Ldarg_2 = 0x04,
    Ldarg_3 = 0x05,
    Ldloc_0 = 0x06,
    Ldloc_1 = 0x07,
    Ldloc_2 = 0x08,
    Ldloc_3 = 0x09,
    Stloc_0 = 0x0A,
    Stloc_1 = 0x0B,
    Stloc_2 = 0x0C,
    Stloc_3 = 0x0D,
    Ldarg_s = 0x0E,
    Ldarga_s = 0x0F,
    Starg_s = 0x10,
    Ldloc_s = 0x11,
    Ldloca_s = 0x12,
    Stloc_s = 0x13,
    Ldnull = 0x14,
    Ldc_i4_M1 = 0x15,
    Ldc_i4_m1 = 0x15,
    Ldc_i4_0 = 0x16,
    Ldc_i4_1 = 0x17,
    Ldc_i4_2 = 0x18,
    Ldc_i4_3 = 0x19,
    Ldc_i4_4 = 0x1A,
    Ldc_i4_5 = 0x1B,
    Ldc_i4_6 = 0x1C,
    Ldc_i4_7 = 0x1D,
    Ldc_i4_8 = 0x1E,
    Ldc_i4_s = 0x1F,
    Ldc_i4 = 0x20,
    Ldc_i8 = 0x21,
    Ldc_r4 = 0x22,
    Ldc_r8 = 0x23,
    dup = 0x25,
    pop = 0x26,
    Jmp = 0x27,
    Call = 0x28,
    Calli = 0x29,
    Ret = 0x2A,
    Br_s = 0x2B,
    Brfalse_s = 0x2C,
    Brinst_s = 0x2D,
    Beq_s = 0x2E,
    Bge_s = 0x2F,
    Bgt_s = 0x30,
    Ble_s = 0x31,
    Blt_s = 0x32,
    Bne_un_s = 0x33,
    Bge_un_s = 0x34,
    Bgt_un_s = 0x35,
    Ble_un_s = 0x36,
    Blt_un_s = 0x37,
    Br = 0x38,
    Brfalse = 0x39,
    Brinst = 0x3A,
    Beq = 0x3B,
    Bge = 0x3C,
    Bgt = 0x3D,
    Ble = 0x3E,
    Blt = 0x3F,
    Bne_un = 0x40,
    Bge_un = 0x41,
    Bgt_un = 0x42,
    Ble_un = 0x43,
    Blt_un = 0x44,
    Switch = 0x45,
    Ldind_i1 = 0x46,
    Ldind_u1 = 0x47,
    Ldind_i2 = 0x48,
    Ldind_u2 = 0x49,
    Ldind_i4 = 0x4A,
    Ldind_u4 = 0x4B,
    Ldind_i8 = 0x4C,
    Ldind_u8 = 0x4C,
    Ldind_i = 0x4D,
    Ldind_r4 = 0x4E,
    Ldind_r8 = 0x4F,
    Ldind_ref = 0x50,
    Stind_ref = 0x51,
    Stind_i1 = 0x52,
    Stind_i2 = 0x53,
    Stind_i4 = 0x54,
    Stind_i8 = 0x55,
    Stind_r4 = 0x56,
    Stind_r8 = 0x57,
    Add = 0x58,
    Sub = 0x59,
    Mul = 0x5A,
    div = 0x5B,
    div_un = 0x5C,
    Rem = 0x5D,
    Rem_un = 0x5E,
    And = 0x5F,
    Or = 0x60,
    xor = 0x61,
    Shl = 0x62,
    Shr = 0x63,
    Shr_un = 0x64,
    Neg = 0x65,
    Not = 0x66,
    Conv_i1 = 0x67,
    Conv_i2 = 0x68,
    Conv_i4 = 0x69,
    Conv_i8 = 0x6A,
    Conv_r4 = 0x6B,
    Conv_r8 = 0x6C,
    Conv_u4 = 0x6D,
    Conv_u8 = 0x6E,
    Callvirt = 0x6F,
    Cpobj = 0x70,
    Ldobj = 0x71,
    Ldstr = 0x72,
    Newobj = 0x73,
    Castclass = 0x74,
    Isinst = 0x75,
    Conv_r_un = 0x76,
    Unbox = 0x79,
    Throw = 0x7A,
    Ldfld = 0x7B,
    Ldflda = 0x7C,
    Stfld = 0x7D,
    Ldsfld = 0x7E,
    Ldsflda = 0x7F,
    Stsfld = 0x80,
    Stobj = 0x81,
    Conv_ovf_i1_un = 0x82,
    Conv_ovf_i2_un = 0x83,
    Conv_ovf_i4_un = 0x84,
    Conv_ovf_i8_un = 0x85,
    Conv_ovf_u1_un = 0x86,
    Conv_ovf_u2_un = 0x87,
    Conv_ovf_u4_un = 0x88,
    Conv_ovf_u8_un = 0x89,
    Conv_ovf_i_un = 0x8A,
    Conv_ovf_u_un = 0x8B,
    Box = 0x8C,
    Newarr = 0x8D,
    Ldlen = 0x8E,
    Ldelema = 0x8F,
    Ldelem_i1 = 0x90,
    Ldelem_u1 = 0x91,
    Ldelem_i2 = 0x92,
    Ldelem_u2 = 0x93,
    Ldelem_i4 = 0x94,
    Ldelem_u4 = 0x95,
    Ldelem_i8 = 0x96,
    Ldelem_u8 = 0x96,
    Ldelem_i = 0x97,
    Ldelem_r4 = 0x98,
    Ldelem_r8 = 0x99,
    Ldelem_ref = 0x9A,
    Stelem_i = 0x9B,
    Stelem_i1 = 0x9C,
    Stelem_i2 = 0x9D,
    Stelem_i4 = 0x9E,
    Stelem_i8 = 0x9F,
    Stelem_r4 = 0xA0,
    Stelem_r8 = 0xA1,
    Stelem_ref = 0xA2,
    Ldelem = 0xA3,
    Stelem = 0xA4,
    Unbox_any = 0xA5,
    Conv_ovf_i1 = 0xB3,
    Conv_ovf_u1 = 0xB4,
    Conv_ovf_i2 = 0xB5,
    Conv_ovf_u2 = 0xB6,
    Conv_ovf_i4 = 0xB7,
    Conv_ovf_u4 = 0xB8,
    Conv_ovf_i8 = 0xB9,
    Conv_ovf_u8 = 0xBA,
    Refanyval = 0xC2,
    Ckfinite = 0xC3,
    Mkrefany = 0xC6,
    Ldtoken = 0xD0,
    Conv_u2 = 0xD1,
    Conv_u1 = 0xD2,
    Conv_i = 0xD3,
    Conv_ovf_i = 0xD4,
    Conv_ovf_u = 0xD5,
    Add_ovf = 0xD6,
    Add_ovf_un = 0xD7,
    Mul_ovf = 0xD8,
    Mul_ovf_un = 0xD9,
    Sub_ovf = 0xDA,
    Sub_ovf_un = 0xDB,
    Endfault = 0xDC,
    Endfinally = 0xDC,
    Leave = 0xDD,
    Leave_s = 0xDE,
    Stind_i = 0xDF,
    Conv_u = 0xE0,
    Arglist = 0xFE00,
    Ceq = 0xFE01,
    Cgt = 0xFE02,
    Cgt_un = 0xFE03,
    Clt = 0xFE04,
    Clt_un = 0xFE05,
    Ldftn = 0xFE06,
    Ldvirtftn = 0xFE07,
    Ldarg = 0xFE09,
    Ldarga = 0xFE0A,
    Starg = 0xFE0B,
    Ldloc = 0xFE0C,
    Ldloca = 0xFE0D,
    Stloc = 0xFE0E,
    Localloc = 0xFE0F,
    Endfilter = 0xFE11,
    Unaligned_ = 0xFE12,
    Volatile_=0xFE13,
    Tail_=0xFE14,
    Initobj = 0xFE15,
    Constrained_ = 0xFE16,
    Cpblk = 0xFE17,
    Initblk = 0xFE18,
    No_ = 0xFE19,
    Rethrow = 0xFE1A,
    Sizeof = 0xFE1C,
    Refanytype = 0xFE1D,
    Readonly_=0xFE1E
};

//List<Dictionary<string, string>> lists = new List<Dictionary<string, string>> {
//new () { {"id", "0x01"}, {"name", "break"},{"desc", "Inform a debugger that a breakpoint has been reached."},{"type", "Base instruction"}},
//new () { {"id", "0x02"}, {"name", "ldarg.0"},{"desc", "Load argument 0 onto the stack."},{"type", "Base instruction"}},
//new () { {"id", "0x03"}, {"name", "ldarg.1"},{"desc", "Load argument 1 onto the stack."},{"type", "Base instruction"}},
//new () { {"id", "0x04"}, {"name", "ldarg.2"},{"desc", "Load argument 2 onto the stack."},{"type", "Base instruction"}},
//new () { {"id", "0x05"}, {"name", "ldarg.3"},{"desc", "Load argument 3 onto the stack."},{"type", "Base instruction"}},
//new () { {"id", "0x06"}, {"name", "ldloc.0"},{"desc", "Load local variable 0 onto stack."},{"type", "Base instruction"}},
//new () { {"id", "0x07"}, {"name", "ldloc.1"},{"desc", "Load local variable 1 onto stack."},{"type", "Base instruction"}},
//new () { {"id", "0x08"}, {"name", "ldloc.2"},{"desc", "Load local variable 2 onto stack."},{"type", "Base instruction"}},
//new () { {"id", "0x09"}, {"name", "ldloc.3"},{"desc", "Load local variable 3 onto stack."},{"type", "Base instruction"}},
//new() { {"id", "0x0A"}, {"name", "stloc.0"},{"desc", "Pop a value from stack into local variable 0."},{"type", "Base instruction"}},
//new() { {"id", "0x0B"}, {"name", "stloc.1"},{"desc", "Pop a value from stack into local variable 1."},{"type", "Base instruction"}},
//new() { {"id", "0x0C"}, {"name", "stloc.2"},{"desc", "Pop a value from stack into local variable 2."},{"type", "Base instruction"}},
//new() { {"id", "0x0D"}, {"name", "stloc.3"},{"desc", "Pop a value from stack into local variable 3."},{"type", "Base instruction"}},
//new () { {"id", "0x0E"}, {"name", "ldarg.s <uint8 (num)>"},{"desc", "Load argument numbered num onto the stack, short form."},{"type", "Base instruction"}},
//new () { {"id", "0x0F"}, {"name", "ldarga.s <uint8 (argNum)>"},{"desc", "Fetch the address of argument argNum, short form."},{"type", "Base instruction"}},
//new() { {"id", "0x10"}, {"name", "starg.s <uint8 (num)>"},{"desc", "Store value to the argument numbered num, short form."},{"type", "Base instruction"}},
//new () { {"id", "0x11"}, {"name", "ldloc.s <uint8 (indx)>"},{"desc", "Load local variable of index indx onto stack, short form."},{"type", "Base instruction"}},
//new () { {"id", "0x12"}, {"name", "ldloca.s <uint8 (indx)>"},{"desc", "Load address of local variable with index indx, short form."},{"type", "Base instruction"}},
//new() { {"id", "0x13"}, {"name", "stloc.s <uint8 (indx)>"},{"desc", "Pop a value from stack into local variable indx, short form."},{"type", "Base instruction"}},
//new () { {"id", "0x14"}, {"name", "ldnull"},{"desc", "Push a null reference on the stack."},{"type", "Base instruction"}},
//new () { {"id", "0x15"}, {"name", "ldc.i4.M1"},{"desc", "Push -1 onto the stack as int32 (alias for ldc.i4.m1)."},{"type", "Base instruction"}},
//new () { {"id", "0x15"}, {"name", "ldc.i4.m1"},{"desc", "Push -1 onto the stack as int32."},{"type", "Base instruction"}},
//new () { {"id", "0x16"}, {"name", "ldc.i4.0"},{"desc", "Push 0 onto the stack as int32."},{"type", "Base instruction"}},
//new () { {"id", "0x17"}, {"name", "ldc.i4.1"},{"desc", "Push 1 onto the stack as int32."},{"type", "Base instruction"}},
//new () { {"id", "0x18"}, {"name", "ldc.i4.2"},{"desc", "Push 2 onto the stack as int32."},{"type", "Base instruction"}},
//new () { {"id", "0x19"}, {"name", "ldc.i4.3"},{"desc", "Push 3 onto the stack as int32."},{"type", "Base instruction"}},
//new () { {"id", "0x1A"}, {"name", "ldc.i4.4"},{"desc", "Push 4 onto the stack as int32."},{"type", "Base instruction"}},
//new () { {"id", "0x1B"}, {"name", "ldc.i4.5"},{"desc", "Push 5 onto the stack as int32."},{"type", "Base instruction"}},
//new () { {"id", "0x1C"}, {"name", "ldc.i4.6"},{"desc", "Push 6 onto the stack as int32."},{"type", "Base instruction"}},
//new () { {"id", "0x1D"}, {"name", "ldc.i4.7"},{"desc", "Push 7 onto the stack as int32."},{"type", "Base instruction"}},
//new () { {"id", "0x1E"}, {"name", "ldc.i4.8"},{"desc", "Push 8 onto the stack as int32."},{"type", "Base instruction"}},
//new () { {"id", "0x1F"}, {"name", "ldc.i4.s <int8 (num)>"},{"desc", "Push num onto the stack as int32, short form."},{"type", "Base instruction"}},
//new () { {"id", "0x20"}, {"name", "ldc.i4 <int32 (num)>"},{"desc", "Push num of type int32 onto the stack as int32."},{"type", "Base instruction"}},
//new () { {"id", "0x21"}, {"name", "ldc.i8 <int64 (num)>"},{"desc", "Push num of type int64 onto the stack as int64."},{"type", "Base instruction"}},
//new () { {"id", "0x22"}, {"name", "ldc.r4 <float32 (num)>"},{"desc", "Push num of type float32 onto the stack as F."},{"type", "Base instruction"}},
//new () { {"id", "0x23"}, {"name", "ldc.r8 <float64 (num)>"},{"desc", "Push num of type float64 onto the stack as F."},{"type", "Base instruction"}},
//new () { {"id", "0x25"}, {"name", "dup"},{"desc", "Duplicate the value on the top of the stack."},{"type", "Base instruction"}},
//new() { {"id", "0x26"}, {"name", "pop"},{"desc", "Pop value from the stack."},{"type", "Base instruction"}},
//new () { {"id", "0x27"}, {"name", "jmp <method>"},{"desc", "Exit current method and jump to the specified method."},{"type", "Base instruction"}},
//new () { {"id", "0x28"}, {"name", "call <method>"},{"desc", "Call method described by method."},{"type", "Base instruction"}},
//new () { {"id", "0x29"}, {"name", "calli <callsitedescr>"},{"desc", "Call method indicated on the stack with arguments described by callsitedescr."},{"type", "Base instruction"}},
//new() { {"id", "0x2A"}, {"name", "ret"},{"desc", "Return from method, possibly with a value."},{"type", "Base instruction"}},
//new () { {"id", "0x2B"}, {"name", "br.s <int8 (target)>"},{"desc", "Branch to target, short form."},{"type", "Base instruction"}},
//new () { {"id", "0x2C"}, {"name", "brfalse.s <int8 (target)>"},{"desc", "Branch to target if value is zero (false), short form."},{"type", "Base instruction"}},
//new () { {"id", "0x2D"}, {"name", "brinst.s <int8 (target)>"},{"desc", "Branch to target if value is a non-null object reference, short form (alias for brtrue.s)."},{"type", "Base instruction"}},
//new () { {"id", "0x2E"}, {"name", "beq.s <int8 (target)>"},{"desc", "Branch to target if equal, short form."},{"type", "Base instruction"}},
//new () { {"id", "0x2F"}, {"name", "bge.s <int8 (target)>"},{"desc", "Branch to target if greater than or equal to, short form."},{"type", "Base instruction"}},
//new () { {"id", "0x30"}, {"name", "bgt.s <int8 (target)>"},{"desc", "Branch to target if greater than, short form."},{"type", "Base instruction"}},
//new () { {"id", "0x31"}, {"name", "ble.s <int8 (target)>"},{"desc", "Branch to target if less than or equal to, short form."},{"type", "Base instruction"}},
//new () { {"id", "0x32"}, {"name", "blt.s <int8 (target)>"},{"desc", "Branch to target if less than, short form."},{"type", "Base instruction"}},
//new () { {"id", "0x33"}, {"name", "bne.un.s <int8 (target)>"},{"desc", "Branch to target if unequal or unordered, short form."},{"type", "Base instruction"}},
//new () { {"id", "0x34"}, {"name", "bge.un.s <int8 (target)>"},{"desc", "Branch to target if greater than or equal to (unsigned or unordered), short form."},{"type", "Base instruction"}},
//new () { {"id", "0x35"}, {"name", "bgt.un.s <int8 (target)>"},{"desc", "Branch to target if greater than (unsigned or unordered), short form."},{"type", "Base instruction"}},
//new () { {"id", "0x36"}, {"name", "ble.un.s <int8 (target)>"},{"desc", "Branch to target if less than or equal to (unsigned or unordered), short form."},{"type", "Base instruction"}},
//new () { {"id", "0x37"}, {"name", "blt.un.s <int8 (target)>"},{"desc", "Branch to target if less than (unsigned or unordered), short form."},{"type", "Base instruction"}},
//new () { {"id", "0x38"}, {"name", "br <int32 (target)>"},{"desc", "Branch to target."},{"type", "Base instruction"}},
//new () { {"id", "0x39"}, {"name", "brfalse <int32 (target)>"},{"desc", "Branch to target if value is zero (false)."},{"type", "Base instruction"}},
//new () { {"id", "0x3A"}, {"name", "brinst <int32 (target)>"},{"desc", "Branch to target if value is a non-null object reference (alias for brtrue)."},{"type", "Base instruction"}},
//new () { {"id", "0x3B"}, {"name", "beq <int32 (target)>"},{"desc", "Branch to target if equal."},{"type", "Base instruction"}},
//new () { {"id", "0x3C"}, {"name", "bge <int32 (target)>"},{"desc", "Branch to target if greater than or equal to."},{"type", "Base instruction"}},
//new () { {"id", "0x3D"}, {"name", "bgt <int32 (target)>"},{"desc", "Branch to target if greater than."},{"type", "Base instruction"}},
//new () { {"id", "0x3E"}, {"name", "ble <int32 (target)>"},{"desc", "Branch to target if less than or equal to."},{"type", "Base instruction"}},
//new () { {"id", "0x3F"}, {"name", "blt <int32 (target)>"},{"desc", "Branch to target if less than."},{"type", "Base instruction"}},
//new () { {"id", "0x40"}, {"name", "bne.un <int32 (target)>"},{"desc", "Branch to target if unequal or unordered."},{"type", "Base instruction"}},
//new () { {"id", "0x41"}, {"name", "bge.un <int32 (target)>"},{"desc", "Branch to target if greater than or equal to (unsigned or unordered)."},{"type", "Base instruction"}},
//new () { {"id", "0x42"}, {"name", "bgt.un <int32 (target)>"},{"desc", "Branch to target if greater than (unsigned or unordered)."},{"type", "Base instruction"}},
//new () { {"id", "0x43"}, {"name", "ble.un <int32 (target)>"},{"desc", "Branch to target if less than or equal to (unsigned or unordered)."},{"type", "Base instruction"}},
//new () { {"id", "0x44"}, {"name", "blt.un <int32 (target)>"},{"desc", "Branch to target if less than (unsigned or unordered)."},{"type", "Base instruction"}},
//new() { {"id", "0x45"}, {"name", "switch <uint32, int32, int32 (t1..tN)>"},{"desc", "Jump to one of n values."},{"type", "Base instruction"}},
//new () { {"id", "0x46"}, {"name", "ldind.i1"},{"desc", "Indirect load value of type int8 as int32 on the stack."},{"type", "Base instruction"}},
//new () { {"id", "0x47"}, {"name", "ldind.u1"},{"desc", "Indirect load value of type unsigned int8 as int32 on the stack."},{"type", "Base instruction"}},
//new () { {"id", "0x48"}, {"name", "ldind.i2"},{"desc", "Indirect load value of type int16 as int32 on the stack."},{"type", "Base instruction"}},
//new () { {"id", "0x49"}, {"name", "ldind.u2"},{"desc", "Indirect load value of type unsigned int16 as int32 on the stack."},{"type", "Base instruction"}},
//new () { {"id", "0x4A"}, {"name", "ldind.i4"},{"desc", "Indirect load value of type int32 as int32 on the stack."},{"type", "Base instruction"}},
//new () { {"id", "0x4B"}, {"name", "ldind.u4"},{"desc", "Indirect load value of type unsigned int32 as int32 on the stack."},{"type", "Base instruction"}},
//new () { {"id", "0x4C"}, {"name", "ldind.i8"},{"desc", "Indirect load value of type int64 as int64 on the stack."},{"type", "Base instruction"}},
//new () { {"id", "0x4C"}, {"name", "ldind.u8"},{"desc", "Indirect load value of type unsigned int64 as int64 on the stack (alias for ldind.i8)."},{"type", "Base instruction"}},
//new () { {"id", "0x4D"}, {"name", "ldind.i"},{"desc", "Indirect load value of type native int as native int on the stack."},{"type", "Base instruction"}},
//new () { {"id", "0x4E"}, {"name", "ldind.r4"},{"desc", "Indirect load value of type float32 as F on the stack."},{"type", "Base instruction"}},
//new () { {"id", "0x4F"}, {"name", "ldind.r8"},{"desc", "Indirect load value of type float64 as F on the stack."},{"type", "Base instruction"}},
//new () { {"id", "0x50"}, {"name", "ldind.ref"},{"desc", "Indirect load value of type object ref as O on the stack."},{"type", "Base instruction"}},
//new() { {"id", "0x51"}, {"name", "stind.ref"},{"desc", "Store value of type object ref (type O) into memory at address."},{"type", "Base instruction"}},
//new() { {"id", "0x52"}, {"name", "stind.i1"},{"desc", "Store value of type int8 into memory at address."},{"type", "Base instruction"}},
//new() { {"id", "0x53"}, {"name", "stind.i2"},{"desc", "Store value of type int16 into memory at address."},{"type", "Base instruction"}},
//new() { {"id", "0x54"}, {"name", "stind.i4"},{"desc", "Store value of type int32 into memory at address."},{"type", "Base instruction"}},
//new() { {"id", "0x55"}, {"name", "stind.i8"},{"desc", "Store value of type int64 into memory at address."},{"type", "Base instruction"}},
//new() { {"id", "0x56"}, {"name", "stind.r4"},{"desc", "Store value of type float32 into memory at address."},{"type", "Base instruction"}},
//new() { {"id", "0x57"}, {"name", "stind.r8"},{"desc", "Store value of type float64 into memory at address."},{"type", "Base instruction"}},
//new () { {"id", "0x58"}, {"name", "add"},{"desc", "Add two values, returning a new value."},{"type", "Base instruction"}},
//new() { {"id", "0x59"}, {"name", "sub"},{"desc", "Subtract value2 from value1, returning a new value."},{"type", "Base instruction"}},
//new () { {"id", "0x5A"}, {"name", "mul"},{"desc", "Multiply values."},{"type", "Base instruction"}},
//new () { {"id", "0x5B"}, {"name", "div"},{"desc", "Divide two values to return a quotient or floating-point result."},{"type", "Base instruction"}},
//new () { {"id", "0x5C"}, {"name", "div.un"},{"desc", "Divide two values, unsigned, returning a quotient."},{"type", "Base instruction"}},
//new() { {"id", "0x5D"}, {"name", "rem"},{"desc", "Remainder when dividing one value by another."},{"type", "Base instruction"}},
//new() { {"id", "0x5E"}, {"name", "rem.un"},{"desc", "Remainder when dividing one unsigned value by another."},{"type", "Base instruction"}},
//new () { {"id", "0x5F"}, {"name", "and"},{"desc", "Bitwise AND of two integral values, returns an integral value."},{"type", "Base instruction"}},
//new() { {"id", "0x60"}, {"name", "or"},{"desc", "Bitwise OR of two integer values, returns an integer."},{"type", "Base instruction"}},
//new() { {"id", "0x61"}, {"name", "xor"},{"desc", "Bitwise XOR of integer values, returns an integer."},{"type", "Base instruction"} } ,
//new() { {"id", "0x62"}, {"name", "shl"},{"desc", "Shift an integer left (shifting in zeros), return an integer."},{"type", "Base instruction"}},
//new() { {"id", "0x63"}, {"name", "shr"},{"desc", "Shift an integer right (shift in sign), return an integer."},{"type", "Base instruction"}},
//new() { {"id", "0x64"}, {"name", "shr.un"},{"desc", "Shift an integer right (shift in zero), return an integer."},{"type", "Base instruction"}},
//new () { {"id", "0x65"}, {"name", "neg"},{"desc", "Negate value."},{"type", "Base instruction"}},
//new () { {"id", "0x66"}, {"name", "not"},{"desc", "Bitwise complement."},{"type", "Base instruction"}},
//new () { {"id", "0x67"}, {"name", "conv.i1"},{"desc", "Convert to int8, pushing int32 on stack."},{"type", "Base instruction"}},
//new () { {"id", "0x68"}, {"name", "conv.i2"},{"desc", "Convert to int16, pushing int32 on stack."},{"type", "Base instruction"}},
//new () { {"id", "0x69"}, {"name", "conv.i4"},{"desc", "Convert to int32, pushing int32 on stack."},{"type", "Base instruction"}},
//new () { {"id", "0x6A"}, {"name", "conv.i8"},{"desc", "Convert to int64, pushing int64 on stack."},{"type", "Base instruction"}},
//new () { {"id", "0x6B"}, {"name", "conv.r4"},{"desc", "Convert to float32, pushing F on stack."},{"type", "Base instruction"}},
//new () { {"id", "0x6C"}, {"name", "conv.r8"},{"desc", "Convert to float64, pushing F on stack."},{"type", "Base instruction"}},
//new () { {"id", "0x6D"}, {"name", "conv.u4"},{"desc", "Convert to unsigned int32, pushing int32 on stack."},{"type", "Base instruction"}},
//new () { {"id", "0x6E"}, {"name", "conv.u8"},{"desc", "Convert to unsigned int64, pushing int64 on stack."},{"type", "Base instruction"}},
//new () { {"id", "0x6F"}, {"name", "callvirt <method>"},{"desc", "Call a method associated with an object."},{"type", "Object model instruction"}},
//new () { {"id", "0x70"}, {"name", "cpobj <typeTok>"},{"desc", "Copy a value type from src to dest."},{"type", "Object model instruction"}},
//new () { {"id", "0x71"}, {"name", "ldobj <typeTok>"},{"desc", "Copy the value stored at address src to the stack."},{"type", "Object model instruction"}},
//new () { {"id", "0x72"}, {"name", "ldstr <string>"},{"desc", "Push a string object for the literal string."},{"type", "Object model instruction"}},
//new () { {"id", "0x73"}, {"name", "newobj <ctor>"},{"desc", "Allocate an uninitialized object or value type and call ctor."},{"type", "Object model instruction"}},
//new () { {"id", "0x74"}, {"name", "castclass <class>"},{"desc", "Cast obj to class."},{"type", "Object model instruction"}},
//new () { {"id", "0x75"}, {"name", "isinst <class>"},{"desc", "Test if obj is an instance of class, returning null or an instance of that class or interface."},{"type", "Object model instruction"}},
//new () { {"id", "0x76"}, {"name", "conv.r.un"},{"desc", "Convert unsigned integer to floating-point, pushing F on stack."},{"type", "Base instruction"}},
//new() { {"id", "0x79"}, {"name", "unbox <valuetype>"},{"desc", "Extract a value-type from obj, its boxed representation, and push a controlled-mutability managed pointer to it to the top of the stack."},{"type", "Object model instruction"}},
//new() { {"id", "0x7A"}, {"name", "throw"},{"desc", "Throw an exception."},{"type", "Object model instruction"}},
//new () { {"id", "0x7B"}, {"name", "ldfld <field>"},{"desc", "Push the value of field of object (or value type) obj, onto the stack."},{"type", "Object model instruction"}},
//new () { {"id", "0x7C"}, {"name", "ldflda <field>"},{"desc", "Push the address of field of object obj on the stack."},{"type", "Object model instruction"}},
//new() { {"id", "0x7D"}, {"name", "stfld <field>"},{"desc", "Replace the value of field of the object obj with value."},{"type", "Object model instruction"}},
//new () { {"id", "0x7E"}, {"name", "ldsfld <field>"},{"desc", "Push the value of the static field on the stack."},{"type", "Object model instruction"}},
//new () { {"id", "0x7F"}, {"name", "ldsflda <field>"},{"desc", "Push the address of the static field, field, on the stack."},{"type", "Object model instruction"}},
//new() { {"id", "0x80"}, {"name", "stsfld <field>"},{"desc", "Replace the value of the static field with val."},{"type", "Object model instruction"}},
//new() { {"id", "0x81"}, {"name", "stobj <typeTok>"},{"desc", "Store a value of type typeTok at an address."},{"type", "Object model instruction"}},
//new () { {"id", "0x82"}, {"name", "conv.ovf.i1.un"},{"desc", "Convert unsigned to an int8 (on the stack as int32) and throw an exception on overflow."},{"type", "Base instruction"}},
//new () { {"id", "0x83"}, {"name", "conv.ovf.i2.un"},{"desc", "Convert unsigned to an int16 (on the stack as int32) and throw an exception on overflow."},{"type", "Base instruction"}},
//new () { {"id", "0x84"}, {"name", "conv.ovf.i4.un"},{"desc", "Convert unsigned to an int32 (on the stack as int32) and throw an exception on overflow."},{"type", "Base instruction"}},
//new () { {"id", "0x85"}, {"name", "conv.ovf.i8.un"},{"desc", "Convert unsigned to an int64 (on the stack as int64) and throw an exception on overflow."},{"type", "Base instruction"}},
//new () { {"id", "0x86"}, {"name", "conv.ovf.u1.un"},{"desc", "Convert unsigned to an unsigned int8 (on the stack as int32) and throw an exception on overflow."},{"type", "Base instruction"}},
//new () { {"id", "0x87"}, {"name", "conv.ovf.u2.un"},{"desc", "Convert unsigned to an unsigned int16 (on the stack as int32) and throw an exception on overflow."},{"type", "Base instruction"}},
//new () { {"id", "0x88"}, {"name", "conv.ovf.u4.un"},{"desc", "Convert unsigned to an unsigned int32 (on the stack as int32) and throw an exception on overflow."},{"type", "Base instruction"}},
//new () { {"id", "0x89"}, {"name", "conv.ovf.u8.un"},{"desc", "Convert unsigned to an unsigned int64 (on the stack as int64) and throw an exception on overflow."},{"type", "Base instruction"}},
//new () { {"id", "0x8A"}, {"name", "conv.ovf.i.un"},{"desc", "Convert unsigned to a native int (on the stack as native int) and throw an exception on overflow."},{"type", "Base instruction"}},
//new () { {"id", "0x8B"}, {"name", "conv.ovf.u.un"},{"desc", "Convert unsigned to a native unsigned int (on the stack as native int) and throw an exception on overflow."},{"type", "Base instruction"}},
//new () { {"id", "0x8C"}, {"name", "box <typeTok>"},{"desc", "Convert a boxable value to its boxed form."},{"type", "Object model instruction"}},
//new () { {"id", "0x8D"}, {"name", "newarr <etype>"},{"desc", "Create a new array with elements of type etype."},{"type", "Object model instruction"}},
//new () { {"id", "0x8E"}, {"name", "ldlen"},{"desc", "Push the length (of type native unsigned int) of array on the stack."},{"type", "Object model instruction"}},
//new () { {"id", "0x8F"}, {"name", "ldelema <class>"},{"desc", "Load the address of element at index onto the top of the stack."},{"type", "Object model instruction"}},
//new () { {"id", "0x90"}, {"name", "ldelem.i1"},{"desc", "Load the element with type int8 at index onto the top of the stack as an int32."},{"type", "Object model instruction"}},
//new () { {"id", "0x91"}, {"name", "ldelem.u1"},{"desc", "Load the element with type unsigned int8 at index onto the top of the stack as an int32."},{"type", "Object model instruction"}},
//new () { {"id", "0x92"}, {"name", "ldelem.i2"},{"desc", "Load the element with type int16 at index onto the top of the stack as an int32."},{"type", "Object model instruction"}},
//new () { {"id", "0x93"}, {"name", "ldelem.u2"},{"desc", "Load the element with type unsigned int16 at index onto the top of the stack as an int32."},{"type", "Object model instruction"}},
//new () { {"id", "0x94"}, {"name", "ldelem.i4"},{"desc", "Load the element with type int32 at index onto the top of the stack as an int32."},{"type", "Object model instruction"}},
//new () { {"id", "0x95"}, {"name", "ldelem.u4"},{"desc", "Load the element with type unsigned int32 at index onto the top of the stack as an int32."},{"type", "Object model instruction"}},
//new () { {"id", "0x96"}, {"name", "ldelem.i8"},{"desc", "Load the element with type int64 at index onto the top of the stack as an int64."},{"type", "Object model instruction"}},
//new () { {"id", "0x96"}, {"name", "ldelem.u8"},{"desc", "Load the element with type unsigned int64 at index onto the top of the stack as an int64 (alias for ldelem.i8)."},{"type", "Object model instruction"}},
//new () { {"id", "0x97"}, {"name", "ldelem.i"},{"desc", "Load the element with type native int at index onto the top of the stack as a native int."},{"type", "Object model instruction"}},
//new () { {"id", "0x98"}, {"name", "ldelem.r4"},{"desc", "Load the element with type float32 at index onto the top of the stack as an F."},{"type", "Object model instruction"}},
//new () { {"id", "0x99"}, {"name", "ldelem.r8"},{"desc", "Load the element with type float64 at index onto the top of the stack as an F."},{"type", "Object model instruction"}},
//new () { {"id", "0x9A"}, {"name", "ldelem.ref"},{"desc", "Load the element at index onto the top of the stack as an O. The type of the O is the same as the element type of the array pushed on the CIL stack."},{"type", "Object model instruction"}},
//new() { {"id", "0x9B"}, {"name", "stelem.i"},{"desc", "Replace array element at index with the native int value on the stack."},{"type", "Object model instruction"}},
//new() { {"id", "0x9C"}, {"name", "stelem.i1"},{"desc", "Replace array element at index with the int8 value on the stack."},{"type", "Object model instruction"}},
//new() { {"id", "0x9D"}, {"name", "stelem.i2"},{"desc", "Replace array element at index with the int16 value on the stack."},{"type", "Object model instruction"}},
//new() { {"id", "0x9E"}, {"name", "stelem.i4"},{"desc", "Replace array element at index with the int32 value on the stack."},{"type", "Object model instruction"}},
//new() { {"id", "0x9F"}, {"name", "stelem.i8"},{"desc", "Replace array element at index with the int64 value on the stack."},{"type", "Object model instruction"}},
//new() { {"id", "0xA0"}, {"name", "stelem.r4"},{"desc", "Replace array element at index with the float32 value on the stack."},{"type", "Object model instruction"}},
//new() { {"id", "0xA1"}, {"name", "stelem.r8"},{"desc", "Replace array element at index with the float64 value on the stack."},{"type", "Object model instruction"}},
//new() { {"id", "0xA2"}, {"name", "stelem.ref"},{"desc", "Replace array element at index with the ref value on the stack."},{"type", "Object model instruction"}},
//new () { {"id", "0xA3"}, {"name", "ldelem <typeTok>"},{"desc", "Load the element at index onto the top of the stack."},{"type", "Object model instruction"}},
//new() { {"id", "0xA4"}, {"name", "stelem <typeTok>"},{"desc", "Replace array element at index with the value on the stack."},{"type", "Object model instruction"}},
//new() { {"id", "0xA5"}, {"name", "unbox.any <typeTok>"},{"desc", "Extract a value-type from obj, its boxed representation, and copy to the top of the stack."},{"type", "Object model instruction"}},
//new () { {"id", "0xB3"}, {"name", "conv.ovf.i1"},{"desc", "Convert to an int8 (on the stack as int32) and throw an exception on overflow."},{"type", "Base instruction"}},
//new () { {"id", "0xB4"}, {"name", "conv.ovf.u1"},{"desc", "Convert to an unsigned int8 (on the stack as int32) and throw an exception on overflow."},{"type", "Base instruction"}},
//new () { {"id", "0xB5"}, {"name", "conv.ovf.i2"},{"desc", "Convert to an int16 (on the stack as int32) and throw an exception on overflow."},{"type", "Base instruction"}},
//new () { {"id", "0xB6"}, {"name", "conv.ovf.u2"},{"desc", "Convert to an unsigned int16 (on the stack as int32) and throw an exception on overflow."},{"type", "Base instruction"}},
//new () { {"id", "0xB7"}, {"name", "conv.ovf.i4"},{"desc", "Convert to an int32 (on the stack as int32) and throw an exception on overflow."},{"type", "Base instruction"}},
//new () { {"id", "0xB8"}, {"name", "conv.ovf.u4"},{"desc", "Convert to an unsigned int32 (on the stack as int32) and throw an exception on overflow."},{"type", "Base instruction"}},
//new () { {"id", "0xB9"}, {"name", "conv.ovf.i8"},{"desc", "Convert to an int64 (on the stack as int64) and throw an exception on overflow."},{"type", "Base instruction"}},
//new () { {"id", "0xBA"}, {"name", "conv.ovf.u8"},{"desc", "Convert to an unsigned int64 (on the stack as int64) and throw an exception on overflow."},{"type", "Base instruction"}},
//new() { {"id", "0xC2"}, {"name", "refanyval <type>"},{"desc", "Push the address stored in a typed reference."},{"type", "Object model instruction"}},
//new () { {"id", "0xC3"}, {"name", "ckfinite"},{"desc", "Throw ArithmeticException if value is not a finite number."},{"type", "Base instruction"}},
//new () { {"id", "0xC6"}, {"name", "mkrefany <class>"},{"desc", "Push a typed reference to ptr of type class onto the stack."},{"type", "Object model instruction"}},
//new () { {"id", "0xD0"}, {"name", "ldtoken <token>"},{"desc", "Convert metadata token to its runtime representation."},{"type", "Object model instruction"}},
//new () { {"id", "0xD1"}, {"name", "conv.u2"},{"desc", "Convert to unsigned int16, pushing int32 on stack."},{"type", "Base instruction"}},
//new () { {"id", "0xD2"}, {"name", "conv.u1"},{"desc", "Convert to unsigned int8, pushing int32 on stack."},{"type", "Base instruction"}},
//new () { {"id", "0xD3"}, {"name", "conv.i"},{"desc", "Convert to native int, pushing native int on stack."},{"type", "Base instruction"}},
//new () { {"id", "0xD4"}, {"name", "conv.ovf.i"},{"desc", "Convert to a native int (on the stack as native int) and throw an exception on overflow."},{"type", "Base instruction"}},
//new () { {"id", "0xD5"}, {"name", "conv.ovf.u"},{"desc", "Convert to a native unsigned int (on the stack as native int) and throw an exception on overflow."},{"type", "Base instruction"}},
//new () { {"id", "0xD6"}, {"name", "add.ovf"},{"desc", "Add signed integer values with overflow check."},{"type", "Base instruction"}},
//new () { {"id", "0xD7"}, {"name", "add.ovf.un"},{"desc", "Add unsigned integer values with overflow check."},{"type", "Base instruction"}},
//new () { {"id", "0xD8"}, {"name", "mul.ovf"},{"desc", "Multiply signed integer values. Signed result shall fit in same size."},{"type", "Base instruction"}},
//new () { {"id", "0xD9"}, {"name", "mul.ovf.un"},{"desc", "Multiply unsigned integer values. Unsigned result shall fit in same size."},{"type", "Base instruction"}},
//new() { {"id", "0xDA"}, {"name", "sub.ovf"},{"desc", "Subtract native int from a native int. Signed result shall fit in same size."},{"type", "Base instruction"}},
//new() { {"id", "0xDB"}, {"name", "sub.ovf.un"},{"desc", "Subtract native unsigned int from a native unsigned int. Unsigned result shall fit in same size."},{"type", "Base instruction"}},
//new () { {"id", "0xDC"}, {"name", "endfault"},{"desc", "End fault clause of an exception block."},{"type", "Base instruction"}},
//new () { {"id", "0xDC"}, {"name", "endfinally"},{"desc", "End finally clause of an exception block."},{"type", "Base instruction"}},
//new () { {"id", "0xDD"}, {"name", "leave <int32 (target)>"},{"desc", "Exit a protected region of code."},{"type", "Base instruction"}},
//new () { {"id", "0xDE"}, {"name", "leave.s <int8 (target)>"},{"desc", "Exit a protected region of code, short form."},{"type", "Base instruction"}},
//new() { {"id", "0xDF"}, {"name", "stind.i"},{"desc", "Store value of type native int into memory at address."},{"type", "Base instruction"}},
//new () { {"id", "0xE0"}, {"name", "conv.u"},{"desc", "Convert to native unsigned int, pushing native int on stack."},{"type", "Base instruction"}},
//new () { {"id", "0xFE00"}, {"name", "arglist"},{"desc", "Return argument list handle for the current method."},{"type", "Base instruction"}},
//new () { {"id", "0xFE01"}, {"name", "ceq"},{"desc", "Push 1 (of type int32) if value1 equals value2, else push 0."},{"type", "Base instruction"}},
//new () { {"id", "0xFE02"}, {"name", "cgt"},{"desc", "Push 1 (of type int32) if value1 greater that value2, else push 0."},{"type", "Base instruction"}},
//new () { {"id", "0xFE03"}, {"name", "cgt.un"},{"desc", "Push 1 (of type int32) if value1 greater that value2, unsigned or unordered, else push 0."},{"type", "Base instruction"}},
//new () { {"id", "0xFE04"}, {"name", "clt"},{"desc", "Push 1 (of type int32) if value1 lower than value2, else push 0."},{"type", "Base instruction"}},
//new () { {"id", "0xFE05"}, {"name", "clt.un"},{"desc", "Push 1 (of type int32) if value1 lower than value2, unsigned or unordered, else push 0."},{"type", "Base instruction"}},
//new () { {"id", "0xFE06"}, {"name", "ldftn <method>"},{"desc", "Push a pointer to a method referenced by method, on the stack."},{"type", "Base instruction"}},
//new () { {"id", "0xFE07"}, {"name", "ldvirtftn <method>"},{"desc", "Push address of virtual method on the stack."},{"type", "Object model instruction"}},
//new () { {"id", "0xFE09"}, {"name", "ldarg <uint16 (num)>"},{"desc", "Load argument numbered num onto the stack."},{"type", "Base instruction"}},
//new () { {"id", "0xFE0A"}, {"name", "ldarga <uint16 (argNum)>"},{"desc", "Fetch the address of argument argNum."},{"type", "Base instruction"}},
//new() { {"id", "0xFE0B"}, {"name", "starg <uint16 (num)>"},{"desc", "Store value to the argument numbered num."},{"type", "Base instruction"}},
//new () { {"id", "0xFE0C"}, {"name", "ldloc <uint16 (indx)>"},{"desc", "Load local variable of index indx onto stack."},{"type", "Base instruction"}},
//new () { {"id", "0xFE0D"}, {"name", "ldloca <uint16 (indx)>"},{"desc", "Load address of local variable with index indx."},{"type", "Base instruction"}},
//new() { {"id", "0xFE0E"}, {"name", "stloc <uint16 (indx)>"},{"desc", "Pop a value from stack into local variable indx."},{"type", "Base instruction"}},
//new () { {"id", "0xFE0F"}, {"name", "localloc"},{"desc", "Allocate space from the local memory pool."},{"type", "Base instruction"}},
//new () { {"id", "0xFE11"}, {"name", "endfilter"},{"desc", "End an exception handling filter clause."},{"type", "Base instruction"}},
//new() { {"id", "0xFE12"}, {"name", "unaligned. (alignment)"},{"desc", "Subsequent pointer instruction might be unaligned."},{"type", "Prefix to instruction"}},
//new() { {"id", "0xFE13"}, {"name", "volatile."},{"desc", "Subsequent pointer reference is volatile."},{"type", "Prefix to instruction"}},
//new() { {"id", "0xFE14"}, {"name", "tail."},{"desc", "Subsequent call terminates current method."},{"type", "Prefix to instruction"}},
//new () { {"id", "0xFE15"}, {"name", "initobj <typeTok>"},{"desc", "Initialize the value at address dest."},{"type", "Object model instruction"}},
//new () { {"id", "0xFE16"}, {"name", "constrained. <thisType>"},{"desc", "Call a virtual method on a type constrained to be type T."},{"type", "Prefix to instruction"}},
//new () { {"id", "0xFE17"}, {"name", "cpblk"},{"desc", "Copy data from memory to memory."},{"type", "Base instruction"}},
//new () { {"id", "0xFE18"}, {"name", "initblk"},{"desc", "Set all bytes in a block of memory to a given byte value."},{"type", "Base instruction"}},
//new () { {"id", "0xFE19"}, {"name","no. {typecheck, rangecheck, nullcheck }" },{"desc", "The specified fault check(s) normally performed as part of the execution of the subsequent instruction can/shall be skipped."},{"type", "Prefix to instruction" } },
//new() { {"id", "0xFE1A"}, {"name", "rethrow"},{"desc", "Rethrow the current exception."},{"type", "Object model instruction"}},
//new() { {"id", "0xFE1C"}, {"name", "sizeof <typeTok>"},{"desc", "Push the size, in bytes, of a type as an unsigned int32."},{"type", "Object model instruction"}},
//new() { {"id", "0xFE1D"}, {"name", "refanytype"},{"desc", "Push the type token stored in a typed reference."},{"type", "Object model instruction"}},
//new() { {"id", "0xFE1E"}, {"name", "readonly."},{"desc", "Specify that the subsequent array address operation performs no type check at runtime, and that it returns a controlled-mutability managed pointer."},{ "type", "Prefix to instruction" } }
//};
//foreach (var item in lists)
//{
//    int id;
//    try
//    {
//        id = Convert.ToInt32((string)item["id"]);
//    }
//    catch (Exception ex)
//    {
//        id = int.Parse(item["id"], System.Globalization.NumberStyles.HexNumber);
//    }
//    var name = item["name"];
//    var desc = item["desc"];
//    var type = item["type"];

//    if (opcodes.ContainsKey(id)) throw new InvalidOperationException(item["id"]);
//    opcodes[id] = new Dictionary<string, string>
//        {
//            { "name", name },
//            { "desc", desc },
//            { "type", type }
//        };
//}
