using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

using System;
using System.Collections.Generic;

namespace Zentient.Reflector.Disassembler
{

    public class OpcodeInfo
    {
        public int OpcodeValue { get; set; }
        public bool IsFixedLength { get; set; }
        public int OpcodeLength { get; set; }
        public bool HasInlineOperands { get; set; }
        // Other metadata properties as needed
    }
}
//class Program
//{
//    static void Main(string[] args)
//    {
//        var calculator = new OpcodeLengthCalculator();

//        // Test the calculator with some opcode values
//        int opcode1 = 0x58;
//        int opcode2 = 0xfe09;

//        Console.WriteLine($"Opcode 0x{opcode1:X} Length: {calculator.CalculateOpcodeLength(opcode1)}");
//        Console.WriteLine($"Opcode 0x{opcode2:X} Length: {calculator.CalculateOpcodeLength(opcode2)}");
//    }
//}



namespace Zentient.Reflector
{

    public class OpCodeInfo
    {
        public static Dictionary<int, string> codes = new Dictionary<int, string>
        {
        {0x00, "Nop"},
        {0x01, "Break"},
        {0x02, "Ldarg_0"},
        {0x03, "Ldarg_1"},
        {0x04, "Ldarg_2"},
        {0x05, "Ldarg_3"},
        {0x06, "Ldloc_0"},
        {0x07, "Ldloc_1"},
        {0x08, "Ldloc_2"},
        {0x09, "Ldloc_3"},
        {0x0a, "Stloc_0"},
        {0x0b, "Stloc_1"},
        {0x0c, "Stloc_2"},
        {0x0d, "Stloc_3"},
        {0x0e, "Ldarg_S"},
        {0x0f, "Ldarga_S"},
        {0x10, "Starg_S"},
        {0x11, "Ldloc_S"},
        {0x12, "Ldloca_S"},
        {0x13, "Stloc_S"},
        {0x14, "Ldnull"},
        {0x15, "Ldc_I4_M1"},
        {0x16, "Ldc_I4_0"},
        {0x17, "Ldc_I4_1"},
        {0x18, "Ldc_I4_2"},
        {0x19, "Ldc_I4_3"},
        {0x1a, "Ldc_I4_4"},
        {0x1b, "Ldc_I4_5"},
        {0x1c, "Ldc_I4_6"},
        {0x1d, "Ldc_I4_7"},
        {0x1e, "Ldc_I4_8"},
        {0x1f, "Ldc_I4_S"},
        {0x20, "Ldc_I4"},
        {0x21, "Ldc_I8"},
        {0x22, "Ldc_R4"},
        {0x23, "Ldc_R8"},
        {0x25, "Dup"},
        {0x26, "Pop"},
        {0x27, "Jmp"},
        {0x28, "Call"},
        {0x29, "Calli"},
        {0x2a, "Ret"},
        {0x2b, "Br_S"},
        {0x2c, "Brfalse_S"},
        {0x2d, "Brtrue_S"},
        {0x2e, "Beq_S"},
        {0x2f, "Bge_S"},
        {0x30, "Bgt_S"},
        {0x31, "Ble_S"},
        {0x32, "Blt_S"},
        {0x33, "Bne_Un_S"},
        {0x34, "Bge_Un_S"},
        {0x35, "Bgt_Un_S"},
        {0x36, "Ble_Un_S"},
        {0x37, "Blt_Un_S"},
        {0x38, "Br"},
        {0x39, "Brfalse"},
        {0x3a, "Brtrue"},
        {0x3b, "Beq"},
        {0x3c, "Bge"},
        {0x3d, "Bgt"},
        {0x3e, "Ble"},
        {0x3f, "Blt"},
        {0x40, "Bne_Un"},
        {0x41, "Bge_Un"},
        {0x42, "Bgt_Un"},
        {0x43, "Ble_Un"},
        {0x44, "Blt_Un"},
        {0x45, "Switch"},
        {0x46, "Ldind_I1"},
        {0x47, "Ldind_U1"},
        {0x48, "Ldind_I2"},
        {0x49, "Ldind_U2"},
        {0x4a, "Ldind_I4"},
        {0x4b, "Ldind_U4"},
        {0x4c, "Ldind_I8"},
        {0x4d, "Ldind_I"},
        {0x4e, "Ldind_R4"},
        {0x4f, "Ldind_R8"},
        {0x50, "Ldind_Ref"},
        {0x51, "Stind_Ref"},
        {0x52, "Stind_I1"},
        {0x53, "Stind_I2"},
        {0x54, "Stind_I4"},
        {0x55, "Stind_I8"},
        {0x56, "Stind_R4"},
        {0x57, "Stind_R8"},
        {0x58, "Add"},
        {0x59, "Sub"},
        {0x5a, "Mul"},
        {0x5b, "Div"},
        {0x5c, "Div_Un"},
        {0x5d, "Rem"},
        {0x5e, "Rem_Un"},
        {0x5f, "And"},
        {0x60, "Or"},
        {0x61, "Xor"},
        {0x62, "Shl"},
        {0x63, "Shr"},
        {0x64, "Shr_Un"},
        {0x65, "Neg"},
        {0x66, "Not"},
        {0x67, "Conv_I1"},
        {0x68, "Conv_I2"},
        {0x69, "Conv_I4"},
        {0x6a, "Conv_I8"},
        {0x6b, "Conv_R4"},
        {0x6c, "Conv_R8"},
        {0x6d, "Conv_U4"},
        {0x6e, "Conv_U8"},
        {0x6f, "Callvirt"},
        {0x70, "Cpobj"},
        {0x71, "Ldobj"},
        {0x72, "Ldstr"},
        {0x73, "Newobj"},
        {0x74, "Castclass"},
        {0x75, "Isinst"},
        {0x76, "Conv_R_Un"},
        {0x79, "Unbox"},
        {0x7a, "Throw"},
        {0x7b, "Ldfld"},
        {0x7c, "Ldflda"},
        {0x7d, "Stfld"},
        {0x7e, "Ldsfld"},
        {0x7f, "Ldsflda"},
        {0x80, "Stsfld"},
        {0x81, "Stobj"},
        {0x82, "Conv_Ovf_I1_Un"},
        {0x83, "Conv_Ovf_I2_Un"},
        {0x84, "Conv_Ovf_I4_Un"},
        {0x85, "Conv_Ovf_I8_Un"},
        {0x86, "Conv_Ovf_U1_Un"},
        {0x87, "Conv_Ovf_U2_Un"},
        {0x88, "Conv_Ovf_U4_Un"},
        {0x89, "Conv_Ovf_U8_Un"},
        {0x8a, "Conv_Ovf_I_Un"},
        {0x8b, "Conv_Ovf_U_Un"},
        {0x8c, "Box"},
        {0x8d, "Newarr"},
        {0x8e, "Ldlen"},
        {0x8f, "Ldelema"},
        {0x90, "Ldelem_I1"},
        {0x91, "Ldelem_U1"},
        {0x92, "Ldelem_I2"},
        {0x93, "Ldelem_U2"},
        {0x94, "Ldelem_I4"},
        {0x95, "Ldelem_U4"},
        {0x96, "Ldelem_I8"},
        {0x97, "Ldelem_I"},
        {0x98, "Ldelem_R4"},
        {0x99, "Ldelem_R8"},
        {0x9a, "Ldelem_Ref"},
        {0x9b, "Stelem_I"},
        {0x9c, "Stelem_I1"},
        {0x9d, "Stelem_I2"},
        {0x9e, "Stelem_I4"},
        {0x9f, "Stelem_I8"},
        {0xa0, "Stelem_R4"},
        {0xa1, "Stelem_R8"},
        {0xa2, "Stelem_Ref"},
        {0xa3, "Ldelem"},
        {0xa4, "Stelem"},
        {0xa5, "Unbox_Any"},
        {0xb3, "Conv_Ovf_I1"},
        {0xb4, "Conv_Ovf_U1"},
        {0xb5, "Conv_Ovf_I2"},
        {0xb6, "Conv_Ovf_U2"},
        {0xb7, "Conv_Ovf_I4"},
        {0xb8, "Conv_Ovf_U4"},
        {0xb9, "Conv_Ovf_I8"},
        {0xba, "Conv_Ovf_U8"},
        {0xc2, "Refanyval"},
        {0xc3, "Ckfinite"},
        {0xc6, "Mkrefany"},
        {0xd0, "Ldtoken"},
        {0xd1, "Conv_U2"},
        {0xd2, "Conv_U1"},
        {0xd3, "Conv_I"},
        {0xd4, "Conv_Ovf_I"},
        {0xd5, "Conv_Ovf_U"},
        {0xd6, "Add_Ovf"},
        {0xd7, "Add_Ovf_Un"},
        {0xd8, "Mul_Ovf"},
        {0xd9, "Mul_Ovf_Un"},
        {0xda, "Sub_Ovf"},
        {0xdb, "Sub_Ovf_Un"},
        {0xdc, "Endfinally"},
        {0xdd, "Leave"},
        {0xde, "Leave_S"},
        {0xdf, "Stind_I"},
        {0xe0, "Conv_U"},
        {0xf8, "Prefix7"},
        {0xf9, "Prefix6"},
        {0xfa, "Prefix5"},
        {0xfb, "Prefix4"},
        {0xfc, "Prefix3"},
        {0xfd, "Prefix2"},
        {0xfe, "Prefix1"},
        {0xff, "Prefixref"},
        {0xfe00, "Arglist"},
        {0xfe01, "Ceq"},
        {0xfe02, "Cgt"},
        {0xfe03, "Cgt_Un"},
        {0xfe04, "Clt"},
        {0xfe05, "Clt_Un"},
        {0xfe06, "Ldftn"},
        {0xfe07, "Ldvirtftn"},
        {0xfe09, "Ldarg"},
        {0xfe0a, "Ldarga"},
        {0xfe0b, "Starg"},
        {0xfe0c, "Ldloc"},
        {0xfe0d, "Ldloca"},
        {0xfe0e, "Stloc"},
        {0xfe0f, "Localloc"},
        {0xfe11, "Endfilter"},
        {0xfe12, "Unaligned_"},
        {0xfe13, "Volatile_"},
        {0xfe14, "Tail_"},
        {0xfe15, "Initobj"},
        {0xfe16, "Constrained_"},
        {0xfe17, "Cpblk"},
        {0xfe18, "Initblk"},
        {0xfe1a, "Rethrow"},
        {0xfe1c, "Sizeof"},
        {0xfe1d, "Refanytype"},
        {0xfe1e, "Readonly_"}
    };
}
}
