name: CI/CD

on:
  push:
    branches:
      - main
    tags:
      - 'v*'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: |
            8.0.x
            9.0.x
      - name: Restore
        run: dotnet restore src/templates/templates.csproj
      - name: Build
        run: dotnet build src/templates/templates.csproj --configuration Release --no-restore
      - name: Test
        run: dotnet test src/templates/templates.csproj --no-build --verbosity normal
      - name: Pack
        run: dotnet pack src/templates/templates.csproj --configuration Release --no-build --output ./artifacts
      - name: Docker Build (net8.0)
        run: docker build -f Dockerfile.net8 -t templates:net8 .
      - name: Docker Build (net9.0)
        run: docker build -f Dockerfile.net9 -t templates:net9 .

  publish:
    if: startsWith(github.ref, 'refs/tags/v')
    needs: build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: |
            8.0.x
            9.0.x
      - name: Publish
        run: dotnet nuget push ./artifacts/*.nupkg --api-key ${{ secrets.NUGET_API_KEY }} --source https://api.nuget.org/v3/index.json
