name: Build CI Image

on:
  push:
    branches: [ main ]
    paths:
      - '.github/ci-image/Dockerfile'
  workflow_dispatch:

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - name: 🧾 Checkout repository
        uses: actions/checkout@v4

      - name: 🔢 Extract Git metadata and Build Date
        id: meta
        run: |
          echo "short_sha=$(git rev-parse --short HEAD)" >> $GITHUB_OUTPUT
          echo "semver_tag=$(git describe --tags --abbrev=0 --match 'v[0-9]*' || echo 'v0.1.0')" >> $GITHUB_OUTPUT
          echo "build_date=$(date +'%Y%m%d-%H%M')" >> $GITHUB_OUTPUT

      - name: 🏷 Docker Login to GHCR
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: 🏗 Set up Docker Buildx (for multi-platform builds and caching)
        uses: docker/setup-buildx-action@v3

      - name: 🏗 Build and push Standard CI Image
        uses: docker/build-push-action@v5
        with:
          context: .github/ci-image/
          file: .github/ci-image/Dockerfile
          push: true
          tags: |
            ghcr.io/${{ github.repository_owner }}/zentient-endpoints-ci:latest
            ghcr.io/${{ github.repository_owner }}/zentient-endpoints-ci:${{ steps.meta.outputs.short_sha }}
            ghcr.io/${{ github.repository_owner }}/zentient-endpoints-ci:${{ steps.meta.outputs.build_date }}
          cache-from: type=registry,ref=ghcr.io/${{ github.repository_owner }}/zentient-endpoints-ci:buildcache
          cache-to: type=registry,ref=ghcr.io/${{ github.repository_owner }}/zentient-endpoints-ci:buildcache,mode=max
          build-args: |
            INCLUDE_DEBUG_TOOLS=false
      
      - name: 🏗 Build and push Debug CI Image
        uses: docker/build-push-action@v5
        with:
          context: .github/ci-image/
          file: .github/ci-image/Dockerfile
          push: true
          tags: |
            ghcr.io/${{ github.repository_owner }}/zentient-endpoints-ci:debug-latest
            ghcr.io/${{ github.repository_owner }}/zentient-endpoints-ci:debug-${{ steps.meta.outputs.short_sha }}
            ghcr.io/${{ github.repository_owner }}/zentient-endpoints-ci:debug-${{ steps.meta.outputs.build_date }}
          cache-from: type=registry,ref=ghcr.io/${{ github.repository_owner }}/zentient-endpoints-ci:buildcache-debug
          cache-to: type=registry,ref=ghcr.io/${{ github.repository_owner }}/zentient-endpoints-ci:buildcache-debug,mode=max
          build-args: |
            INCLUDE_DEBUG_TOOLS=true
