---
name: Build and Deploy Documentation

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

permissions:
  contents: write
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  deploy-docs:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Setup .NET SDK
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '9.0.x'

      - name: Restore NuGet Packages
        run: >
          dotnet restore src/MyTestProject.csproj

      - name: Build Project for XML Documentation
        run: >
          dotnet build src/MyTestProject.csproj --configuration Release

      - name: Install DocFX Global Tool
        run: dotnet tool install -g docfx

      - name: Generate API Metadata (Workaround)
        run: |
          if [[ -d api ]]; then
            echo "(DEBUG) Removing existing 'api' directory to ensure clean"
            echo "pack."
            rm -rf api
          fi
          if [[ -d _site ]]; then
            echo "(DEBUG) Removing existing '_site' directory to ensure clean"
            echo "pack."
            rm -rf _site
          fi
          docfx metadata

      - name: Build DocFX Site
        run: docfx build

      - name: Setup Pages
        uses: actions/configure-pages@v5

      - name: Upload Artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: '_site'

      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
