apiRules:
  # Include all public APIs
  - include:
      hasAttribute:
        uid: System.ComponentModel.EditorBrowsableAttribute
        ctorArguments:
          - System.ComponentModel.EditorBrowsableState.Never
      action: exclude
  
  # Exclude internal APIs  
  - exclude:
      uidRegex: \.Internal\.
      type: Namespace
  
  # Exclude test-related types
  - exclude:
      uidRegex: \.Tests?\.
      type: Namespace
      
  # Exclude generated code
  - exclude:
      hasAttribute:
        uid: System.CodeDom.Compiler.GeneratedCodeAttribute
      action: exclude
      
  # Exclude obsolete APIs by default (can be overridden)
  - exclude:
      hasAttribute:
        uid: System.ObsoleteAttribute
      action: exclude
      
  # Include everything else
  - include:
      uidRegex: .*
      type: "*"
