name: GitVersion

on:
  push:
    branches:
      - main
      - develop
      - 'feature/**'
  pull_request:

jobs:
  gitversion:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Install GitVersion
        uses: gittools/actions/gitversion/setup@v0.11.0
        with:
          versionSpec: '5.x'
      - name: Run GitVersion
        uses: gittools/actions/gitversion/execute@v0.11.0
