version: 2
updates:
  - package-ecosystem: "nuget"
    directory: "Src/Results/"
    schedule:
      interval: "weekly"
    open-pull-requests-limit: 5
    ignore:
      - dependency-name: "Microsoft.NET.Test.Sdk"
        versions: ["17.x"]
  - package-ecosystem: "nuget"
    directory: "Src/AspNetCore/"
    schedule:
      interval: "weekly" # Check for updates once a week
    open-pull-requests-limit: 5
    ignore:
      - dependency-name: "Microsoft.NET.Test.Sdk"
        versions: ["17.x"]
