name: Build & Push Docker Images

on:
  push:
    paths:
      - '.github/workflows/docker.yml'
      - '.devcontainer/Dockerfile.codespaces'
      - '.devcontainer/Dockerfile.ci'
  workflow_dispatch:
    inputs:
      enable_debug:
        description: 'Enable debug logging'
        required: false
        default: 'false'

permissions:
  contents: read
  packages: write

jobs:
  build-push-images:
    name: Build & Push Docker Images
    runs-on: ubuntu-latest

    steps:
      - name: Enable GitHub Actions debug mode
        if: ${{ github.event.inputs.enable_debug == 'true' }}
        run: echo "ACTIONS_STEP_DEBUG=true" >> $GITHUB_ENV

      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Show .NET SDK Version (Diagnostic)
        run: dotnet --info

      - name: Validate Dockerfile paths
        id: validate-paths
        run: |
          if [ -f ".devcontainer/Dockerfile.codespaces" ]; then
            echo "codespaces=dockerfile" >> $GITHUB_OUTPUT
          else
            echo "codespaces=skip" >> $GITHUB_OUTPUT
          fi
          if [ -f ".devcontainer/Dockerfile.ci" ]; then
            echo "ci=dockerfile" >> $GITHUB_OUTPUT
          else
            echo "ci=skip" >> $GITHUB_OUTPUT
          fi

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to GHCR
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build & Push Dev Image
        if: steps.validate-paths.outputs.codespaces == 'dockerfile'
        uses: docker/build-push-action@v5
        with:
          context: .
          file: .devcontainer/Dockerfile.codespaces
          push: true
          no-cache: true
          tags: |
            ghcr.io/ulfbou/zentient-dev:latest
            ghcr.io/ulfbou/zentient-dev:${{ github.sha }}

      - name: Skip Dev Image
        if: steps.validate-paths.outputs.codespaces == 'skip'
        run: echo "Skipping Dev Image build — Dockerfile.codespaces not found."

      - name: Build & Push CI Image
        if: steps.validate-paths.outputs.ci == 'dockerfile'
        uses: docker/build-push-action@v5
        with:
          context: .
          file: .devcontainer/Dockerfile.ci
          push: true
          no-cache: true
          tags: |
            ghcr.io/ulfbou/zentient-ci:latest
            ghcr.io/ulfbou/zentient-ci:${{ github.sha }}

      - name: Skip CI Image
        if: steps.validate-paths.outputs.ci == 'skip'
        run: echo "Skipping CI Image build — Dockerfile.ci not found."
